---
version: '3.8'
services:
  jen:
    image: jenkins/jenkins
    ports:
      - 7070:8080
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == Manager


  Qaserver:
    image: tomee
    ports:
      - 4040:8080
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == Worker 1


  ProdServer:
    image: tomee
    ports:
      - 6666:8080
    deploy:
      replicas: 3
      placement:
         constraints:
           - node.hostname == Worker 2

...

